### ISSUE TITLE
Facebook sdk  initialized

### ISSUE THREAD

**Issue by Vicent9920** [wkxjc/LoginManager#1]
你好，请问你在什么地方进行FaceBook SDK初始化的呢？我复制你的代码，发现使用报错，`The Facebook sdk must be initialized before calling activateApp`。但是在你的代码中并未发现`AppEventsLogger.activateApp(this);`以及`FacebookSdk.sdkInitialize(getApplicationContext());`因此特地请教，请抽空答复，谢谢！
--------------------------------------------------------------------------------------------------------
Hello, where did you initialize the FaceBook SDK? I copy your code, I found using an error, but did not find in your code ` AppEventsLogger. ActivateApp (this); ` and ` FacebookSdk. SdkInitialize (getApplicationContext ()); 'so specially consult, please take time to reply, thank you!

**Comment by wkxjc** [comment]
可能是你的 Facebook SDK 版本太低了，较新的 Facebook SDK 都不需要手动调用初始化了
